import type { Metadata } from "next";
import { Sawarabi_Mincho } from "next/font/google";
import "./globals.css";

const test = Sawarabi_Mincho({
  subsets: ["latin"],
  weight: ["400"]
});

export const metadata: Metadata = {
  title: "Job Is Well Co.,Ltd",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${test.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
